---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php for Ubuntu, Red Hat, and CentOS
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
